Main-Menu: "&7Main Menu"
Tag-Menu: "&7Tags &b%collection%"
Close: "&4Close"
Return-Home: "&eReturn Home"
Right: "Right"
Left: "Left"
Locked-Tags: "&eLocked Tags"
Unlocked-Tags: "&eUnlocked Tags"
Select-Tag: "%tag% was selected"
Already-First-Page: "&7You are already in the first page"
Already-Last-Page: "&7You are already in the last page"
Enable-Tag: "&7Click to enable tag"
Disable-Tag: "&7Click to Disable tag"